server:
  port: 8040

spring:
  application:
    name: updateComponent
  datasource:
    url: jdbc:mysql://localhost:3306/components?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: qw123123
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.liang.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl