server:
  port: 8080

spring:
  application:
    name: gateWay

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

zuul:
  routes:
    addComponent: /add/**
    deleteComponent: /delete/**
    updateComponent: /update/**
    selectComponent: /select/**
  prefix: /deepexi-user/api/v1/components
