server:
  port: 8011

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

zuul:
  routes:
    consumer: /deepexi-user/api/v1/**
    provider: /provider/**